### ISSUE TITLE
Server is not installed?

### ISSUE THREAD

**Issue by ISpaikI** [Crazyloon/Enshrouded-Server-Manager#23]
Have a report of a friend who said that the launcher only showed up install server after overwriting 
the old manager version with the new version.
The profile was created with the old version.

**Comment by Crazyloon** [comment]
Can you get some repro steps from them? I can't reproduce the error

**Comment by ISpaikI** [comment]
Was only closing the 0.1.1 and copy in the 0.2.0 and the install server button was shown at start

**Comment by Wells83** [comment]
impossible to install server, code 2x02

**Comment by ISpaikI** [comment]
Complete new install of the the manager?

**Comment by ISpaikI** [comment]
Do you use actual release?

**Comment by Wells83** [comment]
yes downloaded a few minut

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/225d7819-06b2-4c5b-bd4f-85f265cde01d)

**Comment by Wells83** [comment]
if i start : 
![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/0e80c968-749e-49e2-9a0f-fa8fb256fea3)

and there are not exe file in this directory

**Comment by ISpaikI** [comment]
Is your harddrive having enough space?

**Comment by ISpaikI** [comment]
It show up start server but the installation have to be completed. You can use update server to start the installation again or continue it

**Comment by ISpaikI** [comment]
It looks like you had issues by downloading from steamnetwork. Install and update does the same job it look if files are correct and install or update your server software

**Comment by Wells83** [comment]
important point: steam are not instaled on the computer;

i try update or reinstall, nothing else

**Comment by ISpaikI** [comment]
You installed steam cmd and thats the window with the 0x202 error. Try it again with update server button

**Comment by Wells83** [comment]
steam command is good : 

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/9c52ba2d-bddb-414c-964f-b78ac02409fe)

**Comment by ISpaikI** [comment]
After it it should load server files

**Comment by Wells83** [comment]
after loading steam API .. OK, the window close

**Comment by ISpaikI** [comment]
Did you push the update server button?

**Comment by Wells83** [comment]
yes, its my first print screen with code 0x202

**Comment by ISpaikI** [comment]
Try it again with clicking it

**Comment by ISpaikI** [comment]
Did you look for the freespace of your harddrive the files are saved on? I saw its desktop so your main drive

**Comment by Wells83** [comment]
installation on E/

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/f0a623b6-eb7a-4063-ba25-cbc048ba030b)

i think its enought ;)

**Comment by ISpaikI** [comment]
Are those terrabytes? Or gigabites?

**Comment by Wells83** [comment]
gigabites

**Comment by ISpaikI** [comment]
Thats not enough ^^
Server is way bigger than the freespace you have

**Comment by Wells83** [comment]
ok thx for your support, i clean my disk and i retry ;)

**Comment by ISpaikI** [comment]
No problem. Your welcome. If it works you could give feedback, if its not working we are here to support.

**Comment by Wells83** [comment]
Ok, install is good, 

start ok.

i cant add it to steam with my local adress:

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/8f05dea4-7457-45f3-873d-a3f64cb08615)

but when i test with my IP public, its not working :

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/69480c3a-9bf9-4b93-9480-1e098a8d88aa)

i forwards ports to my box :

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/e4313479-3367-40d1-8256-bac1e040ae72)

and my router : 

![image](https://github.com/ISpaikI/Enshrouded-Server-Manager/assets/11405506/465bdbe1-8c36-4952-b7a8-16c89950305a)

so i dont understand (firewall as off on both computer)

**Comment by ISpaikI** [comment]
Change the ip from 0.0.0.0 to your local ip and start the server again

**Comment by ISpaikI** [comment]
Or try using 127.0.0.1

**Comment by ISpaikI** [comment]
- Stop server
- write in ip: 127.0.0.1
- save settings
- start server

**Comment by ISpaikI** [comment]
In steam serverlist:
Lanip:queryport

Your friends:
Internetip:queryport

**Comment by Wells83** [comment]
yes bot haw forward. nothing works, :'(

**Comment by ISpaikI** [comment]
Did you change to 127.0.0.1?
And added into steam serverlist 192.168.2.110:15637

**Comment by ISpaikI** [comment]
Public ip only works for your friends not for you.
And you have to open ports in windows firewall too

**Comment by ISpaikI** [comment]
Joining the server only works through the game after you added it in steam serverlist

**Comment by Wells83** [comment]
192.168.2.110:15637 -> its work for me

i test on my laptop (connect in 4G), impossible to add server with public adress

firewall are disable on server, so ? ????

**Comment by ISpaikI** [comment]
What ip did you set in server settings?

**Comment by Wells83** [comment]
127.0.0.1

**Comment by ISpaikI** [comment]
You can look if you can find your server here:
https://southnode.net/steam-query-tool

**Comment by ISpaikI** [comment]
- stop server
- Try change the name to another name that will be found many times in enshrouded
- search for the name ingame

**Comment by ISpaikI** [comment]
And i hope you search by ip searching for publicIP:queryport

**Comment by Wells83** [comment]
the version of the game is important to see server ?

which version is required?

**Comment by ISpaikI** [comment]
More informations please. There was an update yesterday. You have to close server and update it. After update start again.
Client needs the newest version too.

**Comment by Wells83** [comment]
my client are in 490142, so i think is good :(

**Comment by ISpaikI** [comment]
Server updated?

**Comment by Wells83** [comment]
yeah, its good ! its work, thx ;)

**Comment by ISpaikI** [comment]
No problem :) is it working for your friends now too?

**Comment by ISpaikI** [comment]
Oh and the manager has an update you can download here. Discord messages are working and some bug fixes

**Comment by Wells83** [comment]
nedd a btn to update auto manager :D

**Comment by ISpaikI** [comment]
Put it as an idea in discussion.
We were talking about an updater for the manager a day ago :)
