### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by xXFreeFunXx** [Crazyloon/Enshrouded-Server-Manager#36]
Hello,
I have two suggestions for the Discord function.
1. custom text for each Discord function.
2. embed optional

Thanks for this great feature, ESM is on the right track!

Best regards
FreeFun

**Comment by Crazyloon** [comment]
We're considering some options for customization, but they may not take priority just yet.

**Comment by ISpaikI** [comment]
For the next version we have (WIP):

Server version check:
- button border of update server button
    - green: up to date
    - yellow: needs update
    - red: something went wrong by check/not installed


Discord:
- Added settings for discord to turn on and off:
    - server start
    - server stop
    - server updating
    - backup
- Visual options:
    - Embed / normal text message
- Test discord message button

**Comment by Crazyloon** [comment]
I think allowing the user to configure the custom text to display is still an option worth adding. I'm going to leave this open until Spaik has a chance to consider it also.

**Comment by ISpaikI** [comment]
![192 168 2 125_spaikserver_RealVNC_Viewer_06 02 2024_09_12_26](https://github.com/Crazyloon/Enshrouded-Server-Manager/assets/88611660/0d446336-1513-4b19-ab85-c602c81ef396)
Looking into it right now :)

**Comment by ISpaikI** [comment]
All implemented
