### ISSUE TITLE
Discord settings are not read after update

### ISSUE THREAD

**Issue by xXFreeFunXx** [Crazyloon/Enshrouded-Server-Manager#50]
It seems that the start message is not read correctly from the Discord conifg of ESM.
The error occurs after the update to 0.5.0.

![](https://cdn.discordapp.com/attachments/1106326089569148999/1208083291325075518/Mx8uF7zZL8.png?ex=65e1fe3d&is=65cf893d&hm=d4a3b05bf443927e3b71792087ee6417b479457b895adab5158411d1b0c70c03&l)

**Comment by xXFreeFunXx** [comment]
Found the error, the key was changed in the JSON.
- Old: "serverOnlineMsg"
- New: "serverStartedMsg"

**Comment by Crazyloon** [comment]
Sorry, I didn't think about that when I changed the names. I can change the JSON key back to what it was, or leave it and leave this issue open for others to see for a while. I'll add some messaging to the release notes.

Thank you
