### ISSUE TITLE
Server import function not available on 0.6.6?

### ISSUE THREAD

**Issue by tuvok81** [Crazyloon/Enshrouded-Server-Manager#58]
Hello,
i search the Import function to import a existent Server on the New Version, but i can not find this function?

**Comment by Crazyloon** [comment]
There isn't an import function, but the equivalent is to use restore from backup.

Select the server profile you want to import to.
Select the restore file
Save settings
Then click restore selected file

It will import the file to you save game folder for the selected profile. It will rename the file to be the correct name for dedicated servers.

It works with server files, zip files containing a server file, and directories containing zip files containing server files

**Comment by tuvok81** [comment]
ok thanks
