### ISSUE TITLE
Auto Backup Issue

### ISSUE THREAD

**Issue by jpleasants** [Crazyloon/Enshrouded-Server-Manager#60]
I setup auto-backup for increments of 20 minutes with 144 backups to be retained and saved. I stopped the server using ESM and then restarted ESM, starting the server again. I've waited about an hour but there have been no automatic backups. Is there something else I should do?

I did a manual backup using ESM and that functions properly.

![image](https://github.com/Crazyloon/Enshrouded-Server-Manager/assets/18755133/595589cd-d576-42a1-9545-314abdeef652)

**Comment by ISpaikI** [comment]
Did you click the autobackup folder button or change the view? Could be this is not refreshing.

**Comment by jpleasants** [comment]
Manually refreshing or re-opening folder shows there's no files in the folder

**Comment by tuvok81** [comment]
i have also the problem

**Comment by Crazyloon** [comment]
I just pushed a fix for this in 0.6.7 - Auto-backup wasn't running because of some bad code
