### ISSUE TITLE
Autobackup cancel after the server make a Autorestart

### ISSUE THREAD

**Issue by tuvok81** [Crazyloon/Enshrouded-Server-Manager#62]
Hello,
we have a entry that the server makes every day at 5 clock a backup...
and they make all 120minutes a backup .. after the server is restarted the server make no autobackups
i have see this in my Discord

![grafik](https://github.com/Crazyloon/Enshrouded-Server-Manager/assets/30367063/b7a7c077-7a69-452a-910c-d52a1674128d)

**Comment by Crazyloon** [comment]
Thanks, this is a problem. I'm going to start auto backups again when the server restarts, but I may have to rethink the solution in the future. As of now, an auto-restart will also restart the backup timer.

**Comment by Crazyloon** [comment]
Closing this. The bug should be fixed in 0.6.8
